spring:
  datasource:
    url: jdbc:sqlite:data/kafka-map.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080
  servlet:
    context-path: /kafka-map

default:
  # 初始化安装时的账号
  username: admin
  # 初始化安装时的密码
  password: admin